### ISSUE TITLE
`useSiteMetadata` error when running development server locally

### ISSUE THREAD

**Issue by khaled9z** [WeAreMahsaAmini/Homepage#25]
Hi,

When I run `yarn develop`, and try to hit http://localhost:8000, I see the following error (screenshot) from within `./node_modules`. Any ideas how to solve this?

My local sha is `cbde3ba5da78787225bdf4002f8eac51fd5fcd4c` from the `main` branch.

<img width="1100" alt="Screen Shot 2022-10-07 at 2 37 00 PM" src="https://user-images.githubusercontent.com/1424518/194626602-eeb024f1-b4c3-466d-b57a-a0e31a59e896.png">

**Comment by khaled9z** [comment]
cc @syavash 🙏

**Comment by syavash** [comment]
@forkbombz Could you pull and try one more time?

Also, please make sure you run `yarn` before running `yarn develop`

**Comment by khaled9z** [comment]
Issue, fixed, thanks @syavash!
