### ISSUE TITLE
Adding the dead of the protests section

### ISSUE THREAD

**Issue by allahyar** [WeAreMahsaAmini/Homepage#4]
Hi guys,
We should not forget those who died on the way of this protests.

**Comment by syavash** [comment]
We will be adding it. If anyone is interested in helping, please add a new page under content folder

**Comment by aditya-shelke99** [comment]
I can add that. Can you please specify the details of this feature. What details of the person must be shown, how will we input the person.
Might be some wrong questions because I'm new to open source

**Comment by khaled9z** [comment]
I will work on this today, will be grabbing data from https://iranhr.net/en/, NGO based in Norway.

**Comment by khaled9z** [comment]
[PR](https://github.com/WeAreMahsaAmini/Homepage/pull/30) is ready, waiting for review/merge.

**Comment by syavash** [comment]
This looks great. Will merge it now.
